package FMDE.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.pattern.GeneratedMatcher;
import org.jetbrains.mps.openapi.model.SNode;

/*package*/ class Pattern_thkv2m_a0a0a0f extends GeneratedMatcher {
  public Pattern_thkv2m_a0a0a0f(SNode patternNode) {
    super(patternNode, false);


  }

}
