package FMDE.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsDescriptor;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.runtime.base.BaseScopeProvider;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsContext;
import jetbrains.mps.scope.SimpleRoleScope;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.SNodePointer;

public class GraphMapping_Constraints extends BaseConstraintsDescriptor {
  public GraphMapping_Constraints() {
    super(MetaAdapterFactory.getConcept(0x41ba7664a5f64ebaL, 0xb5f52e676d679bacL, 0x39ca43a5323a325cL, "FMDE.structure.GraphMapping"));
  }

  @Override
  protected Map<SReferenceLink, ReferenceConstraintsDescriptor> getSpecifiedReferences() {
    Map<SReferenceLink, ReferenceConstraintsDescriptor> references = new HashMap<SReferenceLink, ReferenceConstraintsDescriptor>();
    references.put(MetaAdapterFactory.getReferenceLink(0x41ba7664a5f64ebaL, 0xb5f52e676d679bacL, 0x39ca43a5323a325cL, 0x39ca43a5323b8817L, "source"), new BaseReferenceConstraintsDescriptor(MetaIdFactory.refId(0x41ba7664a5f64ebaL, 0xb5f52e676d679bacL, 0x39ca43a5323a325cL, 0x39ca43a5323b8817L), this) {
      @Override
      public boolean hasOwnScopeProvider() {
        return true;
      }
      @Nullable
      @Override
      public ReferenceScopeProvider getScopeProvider() {
        return new BaseScopeProvider() {
          @Override
          public SNodeReference getSearchScopeValidatorNode() {
            return breakingNode_kemwwb_a0a0a0a0a1a0b0a1a2;
          }
          @Override
          public Scope createScope(final IOperationContext operationContext, final ReferenceConstraintsContext _context) {
            return SimpleRoleScope.forNamedElements(SLinkOperations.getTarget(SNodeOperations.getNodeAncestor(_context.getContextNode(), MetaAdapterFactory.getConcept(0x41ba7664a5f64ebaL, 0xb5f52e676d679bacL, 0x39ca43a5323a3257L, "FMDE.structure.GraphFunction"), false, false), MetaAdapterFactory.getReferenceLink(0x41ba7664a5f64ebaL, 0xb5f52e676d679bacL, 0x39ca43a5323a3257L, 0x39ca43a5323a325dL, "source")), MetaAdapterFactory.getContainmentLink(0x41ba7664a5f64ebaL, 0xb5f52e676d679bacL, 0x5b0ece544220fd25L, 0x5b0ece544220fd28L, "elements"));
          }
        };
      }
    });
    references.put(MetaAdapterFactory.getReferenceLink(0x41ba7664a5f64ebaL, 0xb5f52e676d679bacL, 0x39ca43a5323a325cL, 0x39ca43a5323b8819L, "target"), new BaseReferenceConstraintsDescriptor(MetaIdFactory.refId(0x41ba7664a5f64ebaL, 0xb5f52e676d679bacL, 0x39ca43a5323a325cL, 0x39ca43a5323b8819L), this) {
      @Override
      public boolean hasOwnScopeProvider() {
        return true;
      }
      @Nullable
      @Override
      public ReferenceScopeProvider getScopeProvider() {
        return new BaseScopeProvider() {
          @Override
          public SNodeReference getSearchScopeValidatorNode() {
            return breakingNode_kemwwb_a0a0a0a0a1a0b0a2a2;
          }
          @Override
          public Scope createScope(final IOperationContext operationContext, final ReferenceConstraintsContext _context) {
            return SimpleRoleScope.forNamedElements(SLinkOperations.getTarget(SNodeOperations.getNodeAncestor(_context.getContextNode(), MetaAdapterFactory.getConcept(0x41ba7664a5f64ebaL, 0xb5f52e676d679bacL, 0x39ca43a5323a3257L, "FMDE.structure.GraphFunction"), false, false), MetaAdapterFactory.getReferenceLink(0x41ba7664a5f64ebaL, 0xb5f52e676d679bacL, 0x39ca43a5323a3257L, 0x39ca43a5323a3260L, "target")), MetaAdapterFactory.getContainmentLink(0x41ba7664a5f64ebaL, 0xb5f52e676d679bacL, 0x5b0ece544220fd25L, 0x5b0ece544220fd28L, "elements"));
          }
        };
      }
    });
    return references;
  }
  private static SNodePointer breakingNode_kemwwb_a0a0a0a0a1a0b0a1a2 = new SNodePointer("r:779437c5-e421-45ea-b75a-7881977a049b(FMDE.constraints)", "4164215182250165795");
  private static SNodePointer breakingNode_kemwwb_a0a0a0a0a1a0b0a2a2 = new SNodePointer("r:779437c5-e421-45ea-b75a-7881977a049b(FMDE.constraints)", "4164215182250173478");
}
