package FMDE.sandbox;

/*Generated by MPS */

import FMDE.runtime.FinSet;
import FMDE.runtime.TotalFunction;
import java.util.ArrayList;

public class Test {
  public static void main(String[] args) {
    FinSet GG;
    FinSet HH;
    FinSet New;
    TotalFunction g;
    TotalFunction h;
    TotalFunction f;

    GG = new FinSet(new ArrayList<Object>() {
      {
        add("g1");
        add("g2");
        add("g3");
        add("g4");
      }
    });
    HH = new FinSet(new ArrayList<Object>() {
      {
        add("h");
        add("j");
        add("k");
        add("l");
      }
    });
    New = new FinSet(new ArrayList<Object>() {
      {
        add("h");
        add("k");
        add("l");
        add("m");
      }
    });
    g = new TotalFunction(New, GG) {
      {
        addMapping(getSource().get("h"), getTarget().get("g1"));
      }
      {
        addMapping(getSource().get("k"), getTarget().get("g3"));
      }
    };
    h = new TotalFunction(HH, New) {
      {
        addMapping(getSource().get("j"), getTarget().get("h"));
      }
    };
    f = new TotalFunction(HH, GG) {
      {
        addMapping(getSource().get("h"), getTarget().get("g1"));
      }
    };


  }
}
