package FMDE.sandbox;

/*Generated by MPS */

import FMDE.runtime.FinSet;
import FMDE.runtime.TotalFunction;
import java.util.ArrayList;

public class Test {
  public static void main(String[] args) {
    FinSet G1;
    FinSet G2;
    TotalFunction g;

    G1 = new FinSet(new ArrayList<Object>() {
      {
        add("g");
        add("h");
      }
    });
    G2 = new FinSet(new ArrayList<Object>() {
      {
        add("g1");
        add("h1");
      }
    });
    g = new TotalFunction(G1, G2) {
      {
        addMapping(getSource().get("g"), getTarget().get("g1"));
      }
      {
        addMapping(getSource().get("h"), getTarget().get("h1"));
      }
    };


  }
}
