package FMDE.sandbox;

/*Generated by MPS */

import junit.framework.TestCase;
import FMDE.runtime.FinSet;
import FMDE.runtime.TotalFunction;

public class FinSet_Test extends TestCase {
  private FinSet X1;
  private FinSet Y1;
  private FinSet Z1;
  private FinSet X2;
  private FinSet Y2;
  private FinSet Z2;
  private TotalFunction g1;
  private TotalFunction h1;
  private TotalFunction i1;
  private TotalFunction g2;
  private TotalFunction i2;
  private TotalFunction h2;
  public void test_FinSetEquality() throws Exception {
    assert X1.equals(X2);
    assert Y1.equals(Y2);
    assert Z1.equals(Z2);

  }
  public void test_TotalFunctionEquality() throws Exception {
    assert g1.equals(g2);
    assert h1.equals(h2);
    assert i1.equals(i2);
  }
  public void setUp() {
    X1 = new FinSet("X", 'a', 3, "foo");
    Y1 = new FinSet("Y", 1, 2, "blup");
    Z1 = new FinSet("a", "b", "c");

    g1 = new TotalFunction(Y1, X1).addMapping(Y1.get("1"), X1.get("a")).addMapping(Y1.get("2"), X1.get("3")).addMapping(Y1.get("blup"), X1.get("foo"));
    h1 = new TotalFunction(Z1, X1).addMapping(Z1.get("a"), X1.get("3")).addMapping(Z1.get("b"), X1.get("a")).addMapping(Z1.get("c"), X1.get("foo"));
    i1 = new TotalFunction(Z1, Y1).addMapping(Z1.get("a"), Y1.get("blup")).addMapping(Z1.get("b"), Y1.get("blup")).addMapping(Z1.get("c"), Y1.get("blup"));

  }

}
