package FMDE.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Composition = 0;
  public static final int FinSet = 1;
  public static final int FinSetElements = 2;
  public static final int FinSetRendering = 3;
  public static final int Mapping = 4;
  public static final int Project = 5;
  public static final int TotalFunction = 6;
  public static final int TotalFunctionRendering = 7;
  public static final int fmdeLanguage = 8;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x41ba7664a5f64ebaL, 0xb5f52e676d679bacL);
    builder.put(0x7de6eec37a85fedaL, Composition);
    builder.put(0x58075003b8db538aL, FinSet);
    builder.put(0x40c47a43bd1d01b3L, FinSetElements);
    builder.put(0x6be9763e36a5faaL, FinSetRendering);
    builder.put(0x58075003b8dc484bL, Mapping);
    builder.put(0x6be9763e36afbd2L, Project);
    builder.put(0x58075003b8dc4831L, TotalFunction);
    builder.put(0x5baf3deb65d4da17L, TotalFunctionRendering);
    builder.put(0x7f1fce1641f2d776L, fmdeLanguage);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
