package FMDE.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptComposition = createDescriptorForComposition();
  /*package*/ final ConceptDescriptor myConceptFinSet = createDescriptorForFinSet();
  /*package*/ final ConceptDescriptor myConceptFinSetElements = createDescriptorForFinSetElements();
  /*package*/ final ConceptDescriptor myConceptFinSetRendering = createDescriptorForFinSetRendering();
  /*package*/ final ConceptDescriptor myConceptMapping = createDescriptorForMapping();
  /*package*/ final ConceptDescriptor myConceptProject = createDescriptorForProject();
  /*package*/ final ConceptDescriptor myConceptTotalFunction = createDescriptorForTotalFunction();
  /*package*/ final ConceptDescriptor myConceptTotalFunctionRendering = createDescriptorForTotalFunctionRendering();
  /*package*/ final ConceptDescriptor myConceptfmdeLanguage = createDescriptorForfmdeLanguage();
  private final LanguageConceptSwitch myConceptIndex;

  public StructureAspectDescriptor() {
    myConceptIndex = new LanguageConceptSwitch();
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptComposition, myConceptFinSet, myConceptFinSetElements, myConceptFinSetRendering, myConceptMapping, myConceptProject, myConceptTotalFunction, myConceptTotalFunctionRendering, myConceptfmdeLanguage);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myConceptIndex.index(id)) {
      case LanguageConceptSwitch.Composition:
        return myConceptComposition;
      case LanguageConceptSwitch.FinSet:
        return myConceptFinSet;
      case LanguageConceptSwitch.FinSetElements:
        return myConceptFinSetElements;
      case LanguageConceptSwitch.FinSetRendering:
        return myConceptFinSetRendering;
      case LanguageConceptSwitch.Mapping:
        return myConceptMapping;
      case LanguageConceptSwitch.Project:
        return myConceptProject;
      case LanguageConceptSwitch.TotalFunction:
        return myConceptTotalFunction;
      case LanguageConceptSwitch.TotalFunctionRendering:
        return myConceptTotalFunctionRendering;
      case LanguageConceptSwitch.fmdeLanguage:
        return myConceptfmdeLanguage;
      default:
        return null;
    }
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myConceptIndex.index(c);
  }

  private static ConceptDescriptor createDescriptorForComposition() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FMDE", "Composition", 0x41ba7664a5f64ebaL, 0xb5f52e676d679bacL, 0x7de6eec37a85fedaL);
    b.class_(false, false, false);
    b.super_("jetbrains.mps.baseLanguage.structure.Expression", 0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL);
    b.origin("r:a208b3cd-5ffc-485a-a143-275bfdd90278(FMDE.structure)/9072201022726078170");
    b.associate("from", 0x7de6eec37a8601d0L).target(0x41ba7664a5f64ebaL, 0xb5f52e676d679bacL, 0x58075003b8dc4831L).optional(false).origin("9072201022726078928").done();
    b.associate("to", 0x7de6eec37a8601d2L).target(0x41ba7664a5f64ebaL, 0xb5f52e676d679bacL, 0x58075003b8dc4831L).optional(false).origin("9072201022726078930").done();
    b.alias("composition");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFinSet() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FMDE", "FinSet", 0x41ba7664a5f64ebaL, 0xb5f52e676d679bacL, 0x58075003b8db538aL);
    b.class_(false, false, false);
    b.super_("jetbrains.mps.baseLanguage.structure.Expression", 0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:a208b3cd-5ffc-485a-a143-275bfdd90278(FMDE.structure)/6343126577091138442");
    b.aggregate("elements", 0x40c47a43bd1d01d1L).target(0x41ba7664a5f64ebaL, 0xb5f52e676d679bacL, 0x40c47a43bd1d01b3L).optional(true).ordered(true).multiple(true).origin("4666989545216868817").done();
    b.alias("fset");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFinSetElements() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FMDE", "FinSetElements", 0x41ba7664a5f64ebaL, 0xb5f52e676d679bacL, 0x40c47a43bd1d01b3L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:a208b3cd-5ffc-485a-a143-275bfdd90278(FMDE.structure)/4666989545216868787");
    b.alias("fElements");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFinSetRendering() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FMDE", "FinSetRendering", 0x41ba7664a5f64ebaL, 0xb5f52e676d679bacL, 0x6be9763e36a5faaL);
    b.class_(false, false, false);
    b.super_("FMDE.structure.FinSet", 0x41ba7664a5f64ebaL, 0xb5f52e676d679bacL, 0x58075003b8db538aL);
    b.origin("r:a208b3cd-5ffc-485a-a143-275bfdd90278(FMDE.structure)/485992265075548074");
    b.prop("x", 0x6be9763e36a5fc6L, "485992265075548102");
    b.prop("y", 0x6be9763e36a5fc8L, "485992265075548104");
    b.alias("fSetRendering");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMapping() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FMDE", "Mapping", 0x41ba7664a5f64ebaL, 0xb5f52e676d679bacL, 0x58075003b8dc484bL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x33d23ee961a0cbf3L);
    b.origin("r:a208b3cd-5ffc-485a-a143-275bfdd90278(FMDE.structure)/6343126577091201099");
    b.associate("from", 0x40c47a43bd212127L).target(0x41ba7664a5f64ebaL, 0xb5f52e676d679bacL, 0x40c47a43bd1d01b3L).optional(false).origin("4666989545217138983").done();
    b.associate("to", 0x40c47a43bd2292baL).target(0x41ba7664a5f64ebaL, 0xb5f52e676d679bacL, 0x40c47a43bd1d01b3L).optional(false).origin("4666989545217233594").done();
    b.alias("mapping");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForProject() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FMDE", "Project", 0x41ba7664a5f64ebaL, 0xb5f52e676d679bacL, 0x6be9763e36afbd2L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:a208b3cd-5ffc-485a-a143-275bfdd90278(FMDE.structure)/485992265075588050");
    b.aggregate("fSets", 0x6be9763e36afbeeL).target(0x41ba7664a5f64ebaL, 0xb5f52e676d679bacL, 0x58075003b8db538aL).optional(true).ordered(true).multiple(true).origin("485992265075588078").done();
    b.aggregate("TFunctions", 0x5baf3deb65da5261L).target(0x41ba7664a5f64ebaL, 0xb5f52e676d679bacL, 0x58075003b8dc4831L).optional(true).ordered(true).multiple(true).origin("6606567259611222625").done();
    b.alias("project");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTotalFunction() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FMDE", "TotalFunction", 0x41ba7664a5f64ebaL, 0xb5f52e676d679bacL, 0x58075003b8dc4831L);
    b.class_(false, false, false);
    b.super_("jetbrains.mps.baseLanguage.structure.Expression", 0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:a208b3cd-5ffc-485a-a143-275bfdd90278(FMDE.structure)/6343126577091201073");
    b.associate("source", 0x58075003b8ddfac3L).target(0x41ba7664a5f64ebaL, 0xb5f52e676d679bacL, 0x58075003b8db538aL).optional(false).origin("6343126577091312323").done();
    b.associate("target", 0x58075003b8ddfac8L).target(0x41ba7664a5f64ebaL, 0xb5f52e676d679bacL, 0x58075003b8db538aL).optional(false).origin("6343126577091312328").done();
    b.aggregate("mapping", 0x58075003b8dc4848L).target(0x41ba7664a5f64ebaL, 0xb5f52e676d679bacL, 0x58075003b8dc484bL).optional(false).ordered(true).multiple(true).origin("6343126577091201096").done();
    b.alias("tFunction");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTotalFunctionRendering() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FMDE", "TotalFunctionRendering", 0x41ba7664a5f64ebaL, 0xb5f52e676d679bacL, 0x5baf3deb65d4da17L);
    b.class_(false, false, false);
    b.super_("FMDE.structure.TotalFunction", 0x41ba7664a5f64ebaL, 0xb5f52e676d679bacL, 0x58075003b8dc4831L);
    b.origin("r:a208b3cd-5ffc-485a-a143-275bfdd90278(FMDE.structure)/6606567259610864151");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForfmdeLanguage() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FMDE", "fmdeLanguage", 0x41ba7664a5f64ebaL, 0xb5f52e676d679bacL, 0x7f1fce1641f2d776L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:a208b3cd-5ffc-485a-a143-275bfdd90278(FMDE.structure)/9160266762085914486");
    b.aggregate("FinSets", 0x7f1fce1641f2d792L).target(0x41ba7664a5f64ebaL, 0xb5f52e676d679bacL, 0x58075003b8db538aL).optional(false).ordered(true).multiple(true).origin("9160266762085914514").done();
    b.aggregate("TotalFunctions", 0x7f1fce1641f2d794L).target(0x41ba7664a5f64ebaL, 0xb5f52e676d679bacL, 0x58075003b8dc4831L).optional(false).ordered(true).multiple(true).origin("9160266762085914516").done();
    b.aggregate("compositions", 0x7de6eec37a86cddeL).target(0x41ba7664a5f64ebaL, 0xb5f52e676d679bacL, 0x7de6eec37a85fedaL).optional(true).ordered(true).multiple(true).origin("9072201022726131166").done();
    return b.create();
  }
}
