package FMDE.runtime;

/*Generated by MPS */


public class Composition extends TotalFunction {

  public TotalFunction compose(TotalFunction f, TotalFunction g) {
    TotalFunction f_then_g = new TotalFunction(f.getSource(), g.getTarget());
    for (Object x : f.elementMappings.keySet()) {
      Object mapping = g.map(f.map(x));
      if (mapping == null) {
        System.out.println("Functions can not be composed");
      }
      f_then_g.addMapping(x, mapping);
    }
    return f_then_g;
  }

  public boolean isTheSameAs(TotalFunction f) {
    boolean value = false;
    for (Object x : getSource().getElements()) {
      if (map(x) == null) {
        System.out.println("error");
      }
      value = map(x).equals(f.map(x));
    }
    return value;
  }

}
