package FMDE.runtime;

/*Generated by MPS */

import java.util.List;
import java.util.Arrays;

public class FinSet {
  private List<Object> elements;
  public FinSet(List<Object> pElements) {
    this.elements = pElements;
  }
  public FinSet(Object... pElements) {
    this(Arrays.asList(pElements));
  }
  public List<Object> getElements() {
    return elements;
  }
  public Object get(String pElement) {
    try {
      for (Object o1 : elements) {
        if (o1.toString().equals(pElement)) {
          return o1;
        }
      }
    } catch (Exception e) {
    }
    return "nothing found";
  }

  @Override
  public boolean equals(Object p0) {
    FinSet temp = (FinSet) p0;

    for (Object o_element : elements) {
      if (!(temp.elements.contains(o_element))) {
        return false;
      }
    }
    return true;
  }

}
